Source Code/Events_Core.bb
Source Code/Main_Core.bb
Source Code/NPCs_Core.bb

Corrosive decal placement fix
Blink blur reduction fix
Hazmat green gas interaction fix
heavy hazmat suit inventory selection fix
Keter achievement for Apollyon fix
ring and heavy hazmat suit takeofftimer fix

Fixes for Issue 7

---

Source Code/Main_Core.bb

Fix wallet bug

---

Source Code/Main_Core.bb
Source Code/Menu_Core.bb

Better input box

---

Game.bb
Source Code/Language_Core.bb

Fix compile bug

---

Data/local.ini
Map Creator/Source Code/Main_Core_3D.bb
Source Code/INI_Core.bb
Source Code/Main_Core.bb
Source Code/Menu_Core.bb

Although `ErrorLog` does not work perfectly, the error message still can show the latest exception.
you need to download the latest pre-release of blitz3d tss (ziyuecommentary)

Better error message

---

Source Code/Events_Core.bb
Source Code/Map_Core.bb

Heavy stuff can't be worn with the goggles + gear at the same time and Duplicate If statement removed

More SCP-895 optimizations

---

Data/local.ini
Source Code/Language_Core.bb

https://user-images.githubusercontent.com/63241389/211716652-a0b3a679-d2d9-44d3-95f8-21e77b3bb8ab.mp4

Progress for languages

---

Source Code/Main_Core.bb

I think both features would prove to be great additions to the mod. The test code for quick slots needs the rng stuff before it can be implemented properly however. If you don't want the quick slots in then simply remove the code after the ;'s

Add dropping items without closing INV with Right Click. + More

---

Data/local.ini
Source Code/Main_Core.bb
Source Code/Save_Core.bb

Escape Time

---

Source Code/Main_Core.bb

- Can put the pill in wallet like SCP-500-01 can
- Pill now cures the Common Cold

Fix and Buff Pill

---

Changelog.txt
Source Code/NPCs_Core.bb
Source Code/Save_Core.bb

Update Changelog.txt with recent Hazmat Suit changes.

Fix SCP-049 voiceline and TakeOffTimer Save Data

---

Source Code/Main_Core.bb

Instead of infinite stamina, give the player double stamina.

Nerf Very Fine Hazmat Suit

---

Source Code/Main_Core.bb

Smoother stamina cap transition

---

Data/subtitles.ini
Source Code/Subtitles_Core.bb

Better subtitle system

---

Changelog.txt
Data/NPCs.ini
Game.bb
Source Code/Events_Core.bb
Source Code/Items_Core.bb
Source Code/NPCs_Core.bb

- Balance out NPCs damage based on difficulty factor.
- Make Omni Key Card not as free from a Level 6 Key Card by reducing the odds for one.
- Make the vests slightly better against all NPCs that deal damage.
- SCP-714 and Heavy Equipment can resist the bird planes in the Pocket Dimension.

Completely rebalance parts of the game

---

Data/SCP-294.jsonc

New victim to SCP-294 - artoka

Another victim to SCP-294

---

Data/SCP-294.jsonc

Added two new drinks to SCP-294 + fixed typos - artoka

Changes to SCP-294

---

Data/SCP-294.jsonc

Improved SCP-294 drinks

---

Source Code/Events_Core.bb

Made the audio slightly more louder + 
wearing SCP-268 or SCP-714 makes the camera shake a little less - artoka

Minor tweaks to the PD plane

---

Changelog.txt

Fixed a typo in changelog - artoka

Fixed typo

---

Data/achievements.ini

More better descriptions for achievements + fixed typo - artoka

Improved descriptions for achievements

---

Source Code/Events_Core.bb

An image now appears randomly if the player is blinking while in front of SCP-012 - artoka

SCP-012 Psychosis

---

Data/SCP-294.jsonc

Added a new drink to SCP-294 - artoka

Added a new drink to SCP-294

---

Source Code/Events_Core.bb

- Fix #171

---

Source Code/NPCs_Core.bb

SCP-096 can jam doors now - artoka

SCP-096 can now lock doors after opening them

---

Source Code/Subtitles_Core.bb

- Transparent subtitle box
